float:
  any:
  - base_args: ['@metric']
    constructor: DuckDBVSS
    disabled: false
    docker_tag: ann-benchmarks-duckdb_vss
    module: ann_benchmarks.algorithms.duckdb_vss
    name: duckdb_vss
    run_groups:
      M-16:
        arg_groups: [{M: 16, efConstruction: 200}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 200}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
